### ISSUE TITLE
hoa.2d.decoder~ help file crashes Max

### ISSUE THREAD

**Issue by vincentgoudard** [CICM/HoaLibrary-Light#13]
Hi,

Title says it all ... steps to repro : open the help file!
Happens with Max8.1.8 (and Max8.2.0 beta as well) on a Mac running Mojave.
Does not happen with Max8.1.7.

**Comment by eliottparis** [comment]
Hi @vincentgoudard !

Thanks for reporting this! As this issue seems mainly related to the Max implementation of the HoaLibrary, I'm closing it here, but feel free to open a new one in the [HoaLibrary-Max](https://github.com/CICM/HoaLibrary-Max/issues/new) repository instead.

> PS: @pierreguillot and I moved on other projects, so sadly, we don't have time to maintain these libraries anymore for now...
