### ISSUE TITLE
Incompatibility with existing HOA Ambisonics implementations

### ISSUE THREAD

**Issue by kronihias** [CICM/HoaLibrary-Light#3]
Hi,
as already discussed via Email the implementation of the spherical harmonics has some problems..
The 3d implementation is not compatible to other implementations that have become standard (ambix) - as implemented in the ambix vst plugins and O3A by blueripplesound.

One cause:
In https://github.com/CICM/HoaLibrary-Light/blob/master/Sources/Encoder.hpp#L1208 you write 
`m_cos_theta = std::cos(HOA_PI2 + m_elevation);`, this is a wrong conversion from elevation to zenith angle and results in flipping top/bottom. Correctly it should be: `m_cos_theta = std::cos(HOA_PI2 - m_elevation);`

Condon Shortley phase:
You are using somewhere the term `(-1)^degree`, which no other Ambisonics implementation I know of uses. Please remove for compatibility reasons.

Normalization:
the channels with degree=0 seems to be not scaled by `1/sqrt(4*pi)`. 
I would recommend removing the term `1/sqrt(4*pi)` completely, however if you decide to include it please do it consequently.

Best,
Matthias

**Comment by pierreguillot** [comment]
The normalization and the elevation problem were already corrected on the branch [v2.3](bac0b43) (and now [v3](3527437)). I'm working on the other problem.

**Comment by pierreguillot** [comment]
The Condon Shortley phase problem should also be solved on the branch v3 !

**Comment by kronihias** [comment]
As soon as you have a new build for Max I'll test and check.
Thanks, Matthias

**Comment by elsueno** [comment]
Are all these issues fixed in the SN3D Patch from 05/23/2017?

**Comment by pierreguillot** [comment]
Yes
